### ISSUE TITLE
retriedResults undefined

### ISSUE THREAD

**Issue by MichalNemec** [appfeel/node-pushnotifications#182]
Hello, im trying to send notifications to device group (it works), it worked when i passed in just a device token

```
const settings = {
    gcm: {
      id: "...",
      phonegap: false,
    },
    isAlwaysUseFCM: true,
  };
  const push = new PushNotifications(settings);

  const deviceGroups = [];
  deviceGroups.push(
    "..."
  );
  
  push.send(deviceGroups, data, (err, result) => {
    if (err) {
      console.log(err);
      res.status(500).send(JSON.stringify(err, null, 2));
    } else {
      console.log(result[0].message);
      res.status(200).send(`ok`);
    }
  });
```

```
{
    "data": {
        "message": "Bad Gateway"
    },
    "type": "client_error",
    "version": "2"
}


/opt/project/functions/node_modules/node-gcm/lib/sender.js:125
        results[regTokenPositionMap[i]] = retriedResults[i];
                                          ^

TypeError: Cannot read properties of undefined (reading '0')
    at updateResults (/opt/project/functions/node_modules/node-gcm/lib/sender.js:125:43)
    at updateResponse (/opt/project/functions/node_modules/node-gcm/lib/sender.js:118:5)
    at <anonymous> (/opt/project/functions/node_modules/node-gcm/lib/sender.js:64:28)
    at Request._callback (/opt/project/functions/node_modules/node-gcm/lib/sender.js:178:13)
    at Request.self.callback (/opt/project/functions/node_modules/request/request.js:185:22)
    at Request.emit (node:events:513:28)
    at Request.emit (node:domain:489:12)
    at Request.<anonymous> (/opt/project/functions/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:513:28)
    at Request.emit (node:domain:489:12)
```

**Comment by alex-friedl** [comment]
Closed for inactivity.
