### ISSUE TITLE
Node v4.3.2 Error

### ISSUE THREAD

**Issue by brunooomelo** [appfeel/node-pushnotifications#33]
Does not work in NODE version v4.3.2, Error below:

```node-pushnotifications/node_modules/apn/lib/protocol/endpoint.js:17
const CLIENT_PRELUDE = Buffer.from("PRI * HTTP/2.0\r\n\r\nSM\r\n\r\n");
                              ^

TypeError: this is not a typed array.
    at Function.from (native)
    at Object.<anonymous> (/home/bruno/projects/environment-config/node_modules/node-pushnotifications/node_modules/apn/lib/protocol/endpoint.js:17:31)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/bruno/projects/environment-config/node_modules/node-pushnotifications/node_modules/apn/index.js:27:18)
    at Module._compile (module.js:409:26)
```

**Comment by appfeel** [comment]
Node min version is >= 4.6.0.
Lower versions are not supported and will not: it is also a requirement from node-apn, which is a dependency from this module
